language: objective-c
osx_image: xcode10.0
cache: 
  directories:
    - vendor/bundle
    - Pods
before_install:
  - gem install bundler
install:
  - bundle install -j4 --path=vendor/bundle --binstubs=vendor/bin
  - cd Example && pod repo update && bundle exec pod install && cd -
script:
  - cd Example && bundle exec rake test:iphonesimulator:$TEST_IOS_VERSION && cd -
env:
  matrix:
    - TEST_IOS_VERSION=ios12
    - TEST_IOS_VERSION=ios11
